### ISSUE TITLE
500 Internal Server errors: linked plot and some star detail pages.

### ISSUE THREAD

**Issue by jason-neal** [DanielAndreasen/SWEETer-Cat#130]
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
For examples:
Happening on [linked plot](https://sweetercat.herokuapp.com/linked/) page and an random star detail pages.

[kepler-480](https://sweetercat.herokuapp.com/star/Kepler-480/) works
[11 Com](https://sweetercat.herokuapp.com/star/11%20Com/) and [kepler-52](https://sweetercat.herokuapp.com/star/Kepler-52/) are failing...

These might be related to #129 #105...

@DanielAndreasen  Do you get to see an internal server log to see what is maybe happening?

**Comment by DanielAndreasen** [comment]
```
2018-09-14T19:32:12.320257+00:00 heroku[router]: at=info method=GET path="/linked/" host=sweetercat.herokuapp.com request_id=b650335d-055f-4e15-989e-e426b88dc8a2 fwd="87.60.152.135" dyno=web.1 connect=0ms service=2451ms status=500 bytes=456 protocol=https
2018-09-14T19:32:12.323699+00:00 app[web.1]: [2018-09-14 19:32:12,321] ERROR in app: Exception on /linked/ [GET]
2018-09-14T19:32:12.323706+00:00 app[web.1]: Traceback (most recent call last):
2018-09-14T19:32:12.323710+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2018-09-14T19:32:12.323711+00:00 app[web.1]: response = self.full_dispatch_request()
2018-09-14T19:32:12.323713+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-09-14T19:32:12.323715+00:00 app[web.1]: rv = self.handle_user_exception(e)
2018-09-14T19:32:12.323716+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-09-14T19:32:12.323718+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2018-09-14T19:32:12.323719+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2018-09-14T19:32:12.323721+00:00 app[web.1]: raise value
2018-09-14T19:32:12.323722+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-09-14T19:32:12.323724+00:00 app[web.1]: rv = self.dispatch_request()
2018-09-14T19:32:12.323725+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2018-09-14T19:32:12.323727+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2018-09-14T19:32:12.323729+00:00 app[web.1]: File "/app/sweetercat/app.py", line 63, in mpld3_plot
2018-09-14T19:32:12.323730+00:00 app[web.1]: return plot_page_mpld3(df, columns, request)
2018-09-14T19:32:12.323731+00:00 app[web.1]: File "/app/sweetercat/plot.py", line 124, in plot_page_mpld3
2018-09-14T19:32:12.323733+00:00 app[web.1]: plot = fig_to_html(fig)
2018-09-14T19:32:12.323735+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/mpld3/_display.py", line 251, in fig_to_html
2018-09-14T19:32:12.323736+00:00 app[web.1]: figure_json=json.dumps(figure_json, cls=NumpyEncoder),
2018-09-14T19:32:12.323738+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/json/__init__.py", line 238, in dumps
2018-09-14T19:32:12.323739+00:00 app[web.1]: **kw).encode(obj)
2018-09-14T19:32:12.323740+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/json/encoder.py", line 199, in encode
2018-09-14T19:32:12.323742+00:00 app[web.1]: chunks = self.iterencode(o, _one_shot=True)
2018-09-14T19:32:12.323743+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/json/encoder.py", line 257, in iterencode
2018-09-14T19:32:12.323744+00:00 app[web.1]: return _iterencode(o, 0)
2018-09-14T19:32:12.323746+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/mpld3/_display.py", line 138, in default
2018-09-14T19:32:12.323747+00:00 app[web.1]: return json.JSONEncoder.default(self, obj)
2018-09-14T19:32:12.323749+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/json/encoder.py", line 180, in default
2018-09-14T19:32:12.323750+00:00 app[web.1]: o.__class__.__name__)
2018-09-14T19:32:12.323759+00:00 app[web.1]: TypeError: Object of type 'ndarray' is not JSON serializable
```

**Comment by DanielAndreasen** [comment]
It's a bit difficult to see, but it happens at [line 124 here](https://github.com/DanielAndreasen/SWEETer-Cat/blob/master/sweetercat/plot.py#L124). I think it is related to the old issue, unfortunately.
Any good ideas on how to fix it?

**Comment by DanielAndreasen** [comment]
I guess we could do like this: https://stackoverflow.com/a/47382061
Or maybe create the PR ourselves (I see you already asked for this to be done).

**Comment by DanielAndreasen** [comment]
It seems to be fixed with PR #131.

**Comment by jason-neal** [comment]
I am not sure what you did here to resolve it... I had already gotten javadbas fix into mpld3 master and SweeterCat was (supposed to be) pip installing mpld3 from master was already done in master. 

e911985c6ad5a `git+git://github.com/mpld3/mpld3@master#egg=mpld3`  PR #129

8535e4b `git+https://github.com/javadba/mpld3@display_fix`  (Your PR #131)
Then in 
dc02bdb  git+https://github.com/mpld3/mpld3@master
you have changed it back to mpld3 master just changed from the git+#egg=.. to https (does basically the same)

Was it some other requirement that was changed?

**Comment by DanielAndreasen** [comment]
I understand the confusion.
Only think I changed was in fact this
`git+git://github.com/mpld3/mpld3@master#egg=mpld3`
to
`git+https://github.com/mpld3/mpld3@master`

So I guess the `#egg=mpld3` was not working as expected? Or maybe the `git` vs `https`?

**Comment by jason-neal** [comment]
Possibly, it is working now though. 
I am pretty sure you need both parts. e.g. If you call it with `git+git` then needs the `#egg=mpld3` part. 
Some parts of python packaging are still a mystery...
