### ISSUE TITLE
IndexError for HD 564

### ISSUE THREAD

**Issue by DanielAndreasen** [DanielAndreasen/SWEETer-Cat#53]
At `http://localhost:5000/star/HD 564/` the following error occur

```
Traceback (most recent call last):
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daniel/Software/anaconda3/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daniel/Desktop/SWEETer-Cat/sweetercat/app.py", line 73, in stardetail
    show_planet = bool(~d['plName'].isnull().values[0])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Basically a star with that name does not exists, which sounds very strange.

**Comment by jason-neal** [comment]
Yes, it is very strange, I also get this error for the same star.

**Comment by DanielAndreasen** [comment]
The problem is trailing whitespaces in the star name. It is not `HD 564`, but `HD 564--` (<- with two trailing whitespaces)
